### PR TITLE
add initial tabindex to provider

### PR DESCRIPTION
**Pull request by janhesters**
Hi Steve! 👋 

Love your package, it helps us make our apps more accessible 🔥 

I'd love to add this small little feature. In some of our widgets, we remember the users choice, so it would be cool when we could sustain focus by providing an initial index.

This small PR implements that feature.

Let me know what you think!

### CODE REVIEW

**Comment by stevejay** [comment]
Hi! I think adding the ability to restore the last selected tab stop makes a lot of sense 👍 Unfortunately it's actually a bit tricky to implement. The code works using auto-registration, which means if necessary I adjust `selectedId` after each registration (in `getUpdatedSelectedId`). This would currently not play well with an `initialSelectedId` prop. I'll have to think about how this could be fixed.

Also, how would you be tracking the currently selected tab stop in order to then save it somewhere?

BTW thanks for bringing the 'unreachable code' linting error to my attention. It wasn't being flagged up in VS Code because of [this TypeScript change](https://github.com/microsoft/TypeScript/issues/25738).

**Comment by janhesters** [comment]
@stevejay Hi Steve, I'm sorry I couldn't dive deep enough into the code to get foresee this possible bug. Please let me know if I can help somehow with a PR (though I'd need a little guidance 😅 ).

 > Also, how would you be tracking the currently selected tab stop in order to then save it somewhere?

I feel like it wouldn't have to be part of this package and each user could handle that on their own. We are saving the state in local storage (the initial value would come from Redux w/ Redux persist).

> BTW thanks for bringing the 'unreachable code' linting error to my attention. It wasn't being flagged up in VS Code because of this TypeScript change.

Haha, you're welcome!

**Comment by stevejay** [comment]
> I feel like it wouldn't have to be part of this package and each user could handle that on their own.

Yep, agreed. I think another part of the problem is how to expose the selectedIndex for the developer's persistence mechanism.

**Comment by janhesters** [comment]
@stevejay Maybe make it a classic controlled input a la `onIndexChange` and `index`?

**Comment by stevejay** [comment]
@janhesters I've opened a PR with support for setting the initial tabbable element using a selector rather than an index: https://github.com/stevejay/react-roving-tabindex/pull/32 
Please let me know if this works for your use case.

**Pull request closed without merging**
