### PR TITLE
add initialisation support

### PR DESCRIPTION
**Pull request by stevejay**
Published to npm as the latest beta version (2.2.0-beta-1).

### CODE REVIEW

**Comment by jhensley** [comment]
Hi @stevejay curious if you've got a release plan to get this to the mainline release yet? If not, no worries -- we can likely build off the beta version just the same.

**Comment by stevejay** [comment]
@jhensley I was hoping to get feedback from the person who first requested this. If you feel that these additions support your needs then there is no issue with mainlining them 👍 Just let me know.

**Comment by jhensley** [comment]
It's close to what we're looking for ... let me try to explain based on the storybook for this repo (https://stevejay.github.io/react-roving-tabindex/?path=/story/toolbar-rovingtabindex--toolbar-example)

1. Focus on the button (Something before to focus on)
2. Press tab (focus should move to the toolbar, on Button one)
3. Press the right arrow 2x (focus should move to Button four)
4. Press tab (focus should move to Something after to focus on)
5. Press shift tab(focus moves back to Button four)

What we're really looking to do is when you press shift tab, it focus back on Button one... I've looked around and cannot find which is the more correct implementation of roving tab index; simply using Google Sheets as a reference point, it works more as I've described here.

Curious to your thoughts? I'm also happy to open a PR as well.

**Comment by jhensley** [comment]
Looking a little more -- https://www.w3.org/TR/wai-aria-practices/examples/toolbar/toolbar.html specifically mentions the implementation you have ... so I think it's safe to ignore what I've suggested unless you feel like it would make a good configuration/prop option.

**Comment by stevejay** [comment]
@jhensley Ah, okay. That behaviour would IMHO be contrary to the concept of a roving tabindex as implemented in this library. The idea is that the a11y user is able to know that, in your example, tabbing back would focus back on Button Four. It's the button they were last on in the toolbar, and they are put back there. This particular PR was for a different request entirely, for being able to save the current focus position so that it could be restored, e.g., after the user logs back in again.

**Comment by stevejay** [comment]
@jhensley Ooops, I didn't see your last post before making mine; my reply was to [this comment](https://github.com/stevejay/react-roving-tabindex/pull/32#issuecomment-780888632).

**Comment by stevejay** [comment]
Closing due to no feedback.

**Pull request closed without merging**
